name: update_public_data
on:
  push:
    branches: [ master ]
    paths:
      - public/data/**/*

jobs:

  build_index:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - uses: actions/setup-node@v1
      
      - run: |
          yarn 
          yarn build:index

      - uses: actions/upload-artifact@v2
        with:
          name: data_artifact
          path: public/data
  
  deploy_data:
    runs-on: ubuntu-18.04
    needs: build_index
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages

      - run: rm -r data

      - uses: actions/download-artifact@v2
        with:
          name: data_artifact
          path: data

      - run: |
          git config --local user.email "posts_hook@github.com"
          git config --local user.name "Posts Hook"
          git add data
          git commit -m "[CI:deploy] deploy_data job"
          git push -u origin gh-pages
